name: ChatCooldown
author: AhmHkn
main: me.AhmHkn.ChatCooldown.Main
description: Chat cooldown plugin.
version: 1.1
commands:
  cdreload:
    description: Reload command.
permissions:
  chatcooldown.bypass:
    description: Bypass for chat cooldown permission.
    default: op